version: '3.5'

services:
  sharefy-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: sharefy-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 80:80
    networks:
      backend:
        aliases:
          - sharefy-app

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: sharefy-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_sharefy
      MYSQL_ROOT_PASSWORD: Vg(28}Pvhc779N:t
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    name: backend

#Volumes
volumes:
  dbdata:
    driver: local